require('dotenv').config();
const { Airport } = require('../models');

async function seedAirports() {
  try {
    console.log('Starting airport seeding...');

    const airports = [
      // ==================== NORTH AMERICA ====================

      // United States - International Hubs
      {
        icaoCode: 'KJFK',
        iataCode: 'JFK',
        name: 'John F. Kennedy International Airport',
        city: 'New York',
        country: 'United States',
        latitude: 40.6413,
        longitude: -73.7781,
        elevation: 13,
        type: 'International Hub',
        timezone: 'America/New_York',
        operationalFrom: 1948,
        operationalUntil: null
      },
      {
        icaoCode: 'KLAX',
        iataCode: 'LAX',
        name: 'Los Angeles International Airport',
        city: 'Los Angeles',
        country: 'United States',
        latitude: 33.9416,
        longitude: -118.4085,
        elevation: 125,
        type: 'International Hub',
        timezone: 'America/Los_Angeles',
        operationalFrom: 1930,
        operationalUntil: null
      },
      {
        icaoCode: 'KORD',
        iataCode: 'ORD',
        name: "O'Hare International Airport",
        city: 'Chicago',
        country: 'United States',
        latitude: 41.9742,
        longitude: -87.9073,
        elevation: 672,
        type: 'International Hub',
        timezone: 'America/Chicago',
        operationalFrom: 1944,
        operationalUntil: null
      },
      {
        icaoCode: 'KATL',
        iataCode: 'ATL',
        name: 'Hartsfield-Jackson Atlanta International Airport',
        city: 'Atlanta',
        country: 'United States',
        latitude: 33.6407,
        longitude: -84.4277,
        elevation: 1026,
        type: 'International Hub',
        timezone: 'America/New_York',
        operationalFrom: 1926,
        operationalUntil: null
      },
      {
        icaoCode: 'KDFW',
        iataCode: 'DFW',
        name: 'Dallas/Fort Worth International Airport',
        city: 'Dallas',
        country: 'United States',
        latitude: 32.8998,
        longitude: -97.0403,
        elevation: 607,
        type: 'International Hub',
        timezone: 'America/Chicago',
        operationalFrom: 1974,
        operationalUntil: null
      },
      {
        icaoCode: 'KSFO',
        iataCode: 'SFO',
        name: 'San Francisco International Airport',
        city: 'San Francisco',
        country: 'United States',
        latitude: 37.6213,
        longitude: -122.3790,
        elevation: 13,
        type: 'International Hub',
        timezone: 'America/Los_Angeles',
        operationalFrom: 1927,
        operationalUntil: null
      },
      {
        icaoCode: 'KDEN',
        iataCode: 'DEN',
        name: 'Denver International Airport',
        city: 'Denver',
        country: 'United States',
        latitude: 39.8561,
        longitude: -104.6737,
        elevation: 5431,
        type: 'International Hub',
        timezone: 'America/Denver',
        operationalFrom: 1995,
        operationalUntil: null
      },
      {
        icaoCode: 'KMIA',
        iataCode: 'MIA',
        name: 'Miami International Airport',
        city: 'Miami',
        country: 'United States',
        latitude: 25.7959,
        longitude: -80.2870,
        elevation: 8,
        type: 'International Hub',
        timezone: 'America/New_York',
        operationalFrom: 1928,
        operationalUntil: null
      },
      {
        icaoCode: 'KSEA',
        iataCode: 'SEA',
        name: 'Seattle-Tacoma International Airport',
        city: 'Seattle',
        country: 'United States',
        latitude: 47.4502,
        longitude: -122.3088,
        elevation: 433,
        type: 'Major',
        timezone: 'America/Los_Angeles',
        operationalFrom: 1944,
        operationalUntil: null
      },
      {
        icaoCode: 'KBOS',
        iataCode: 'BOS',
        name: 'Logan International Airport',
        city: 'Boston',
        country: 'United States',
        latitude: 42.3656,
        longitude: -71.0096,
        elevation: 20,
        type: 'Major',
        timezone: 'America/New_York',
        operationalFrom: 1923,
        operationalUntil: null
      },
      {
        icaoCode: 'KLAS',
        iataCode: 'LAS',
        name: 'Harry Reid International Airport',
        city: 'Las Vegas',
        country: 'United States',
        latitude: 36.0840,
        longitude: -115.1537,
        elevation: 2181,
        type: 'Major',
        timezone: 'America/Los_Angeles',
        operationalFrom: 1942,
        operationalUntil: null
      },
      {
        icaoCode: 'KPHX',
        iataCode: 'PHX',
        name: 'Phoenix Sky Harbor International Airport',
        city: 'Phoenix',
        country: 'United States',
        latitude: 33.4342,
        longitude: -112.0080,
        elevation: 1135,
        type: 'Major',
        timezone: 'America/Phoenix',
        operationalFrom: 1928,
        operationalUntil: null
      },
      {
        icaoCode: 'KMCO',
        iataCode: 'MCO',
        name: 'Orlando International Airport',
        city: 'Orlando',
        country: 'United States',
        latitude: 28.4312,
        longitude: -81.3081,
        elevation: 96,
        type: 'Major',
        timezone: 'America/New_York',
        operationalFrom: 1942,
        operationalUntil: null
      },
      {
        icaoCode: 'KIAH',
        iataCode: 'IAH',
        name: 'George Bush Intercontinental Airport',
        city: 'Houston',
        country: 'United States',
        latitude: 29.9902,
        longitude: -95.3368,
        elevation: 97,
        type: 'Major',
        timezone: 'America/Chicago',
        operationalFrom: 1969,
        operationalUntil: null
      },
      {
        icaoCode: 'KEWR',
        iataCode: 'EWR',
        name: 'Newark Liberty International Airport',
        city: 'Newark',
        country: 'United States',
        latitude: 40.6925,
        longitude: -74.1687,
        elevation: 18,
        type: 'International Hub',
        timezone: 'America/New_York',
        operationalFrom: 1928,
        operationalUntil: null
      },
      {
        icaoCode: 'KMDW',
        iataCode: 'MDW',
        name: 'Chicago Midway International Airport',
        city: 'Chicago',
        country: 'United States',
        latitude: 41.7868,
        longitude: -87.7522,
        elevation: 620,
        type: 'Major',
        timezone: 'America/Chicago',
        operationalFrom: 1927,
        operationalUntil: null
      },
      {
        icaoCode: 'KDCA',
        iataCode: 'DCA',
        name: 'Ronald Reagan Washington National Airport',
        city: 'Washington',
        country: 'United States',
        latitude: 38.8521,
        longitude: -77.0377,
        elevation: 15,
        type: 'Major',
        timezone: 'America/New_York',
        operationalFrom: 1941,
        operationalUntil: null
      },
      {
        icaoCode: 'KIAD',
        iataCode: 'IAD',
        name: 'Washington Dulles International Airport',
        city: 'Washington',
        country: 'United States',
        latitude: 38.9531,
        longitude: -77.4565,
        elevation: 313,
        type: 'International Hub',
        timezone: 'America/New_York',
        operationalFrom: 1962,
        operationalUntil: null
      },
      {
        icaoCode: 'KBWI',
        iataCode: 'BWI',
        name: 'Baltimore/Washington International Airport',
        city: 'Baltimore',
        country: 'United States',
        latitude: 39.1774,
        longitude: -76.6684,
        elevation: 146,
        type: 'Major',
        timezone: 'America/New_York',
        operationalFrom: 1950,
        operationalUntil: null
      },
      {
        icaoCode: 'KCLT',
        iataCode: 'CLT',
        name: 'Charlotte Douglas International Airport',
        city: 'Charlotte',
        country: 'United States',
        latitude: 35.2144,
        longitude: -80.9473,
        elevation: 748,
        type: 'Major',
        timezone: 'America/New_York',
        operationalFrom: 1935,
        operationalUntil: null
      },
      {
        icaoCode: 'KSAN',
        iataCode: 'SAN',
        name: 'San Diego International Airport',
        city: 'San Diego',
        country: 'United States',
        latitude: 32.7336,
        longitude: -117.1897,
        elevation: 17,
        type: 'Major',
        timezone: 'America/Los_Angeles',
        operationalFrom: 1928,
        operationalUntil: null
      },
      {
        icaoCode: 'KSLC',
        iataCode: 'SLC',
        name: 'Salt Lake City International Airport',
        city: 'Salt Lake City',
        country: 'United States',
        latitude: 40.7884,
        longitude: -111.9778,
        elevation: 4227,
        type: 'Major',
        timezone: 'America/Denver',
        operationalFrom: 1960,
        operationalUntil: null
      },
      {
        icaoCode: 'KDTW',
        iataCode: 'DTW',
        name: 'Detroit Metropolitan Wayne County Airport',
        city: 'Detroit',
        country: 'United States',
        latitude: 42.2124,
        longitude: -83.3534,
        elevation: 645,
        type: 'Major',
        timezone: 'America/Detroit',
        operationalFrom: 1930,
        operationalUntil: null
      },
      {
        icaoCode: 'KMSP',
        iataCode: 'MSP',
        name: 'Minneapolis-St Paul International Airport',
        city: 'Minneapolis',
        country: 'United States',
        latitude: 44.8848,
        longitude: -93.2223,
        elevation: 841,
        type: 'Major',
        timezone: 'America/Chicago',
        operationalFrom: 1920,
        operationalUntil: null
      },
      {
        icaoCode: 'KPDX',
        iataCode: 'PDX',
        name: 'Portland International Airport',
        city: 'Portland',
        country: 'United States',
        latitude: 45.5887,
        longitude: -122.5975,
        elevation: 31,
        type: 'Major',
        timezone: 'America/Los_Angeles',
        operationalFrom: 1940,
        operationalUntil: null
      },
      {
        icaoCode: 'PANC',
        iataCode: 'ANC',
        name: 'Ted Stevens Anchorage International Airport',
        city: 'Anchorage',
        country: 'United States',
        latitude: 61.1744,
        longitude: -149.9962,
        elevation: 152,
        type: 'Regional',
        timezone: 'America/Anchorage',
        operationalFrom: 1951,
        operationalUntil: null
      },
      {
        icaoCode: 'PHNL',
        iataCode: 'HNL',
        name: 'Daniel K. Inouye International Airport',
        city: 'Honolulu',
        country: 'United States',
        latitude: 21.3187,
        longitude: -157.9225,
        elevation: 13,
        type: 'Major',
        timezone: 'Pacific/Honolulu',
        operationalFrom: 1927,
        operationalUntil: null
      },

      // Historical US Airports (Closed)
      {
        icaoCode: 'KCGX',
        iataCode: 'CGX',
        name: 'Meigs Field',
        city: 'Chicago',
        country: 'United States',
        latitude: 41.8586,
        longitude: -87.6076,
        elevation: 593,
        type: 'Small Regional',
        timezone: 'America/Chicago',
        operationalFrom: 1948,
        operationalUntil: 2003
      },
      {
        icaoCode: 'KDAL',
        iataCode: 'DAL',
        name: 'Dallas Love Field',
        city: 'Dallas',
        country: 'United States',
        latitude: 32.8470,
        longitude: -96.8517,
        elevation: 487,
        type: 'Regional',
        timezone: 'America/Chicago',
        operationalFrom: 1917,
        operationalUntil: null
      },
      {
        icaoCode: 'KHOU',
        iataCode: 'HOU',
        name: 'William P. Hobby Airport',
        city: 'Houston',
        country: 'United States',
        latitude: 29.6454,
        longitude: -95.2789,
        elevation: 46,
        type: 'Regional',
        timezone: 'America/Chicago',
        operationalFrom: 1927,
        operationalUntil: null
      },

      // Canada
      {
        icaoCode: 'CYYZ',
        iataCode: 'YYZ',
        name: 'Toronto Pearson International Airport',
        city: 'Toronto',
        country: 'Canada',
        latitude: 43.6777,
        longitude: -79.6248,
        elevation: 569,
        type: 'International Hub',
        timezone: 'America/Toronto',
        operationalFrom: 1939,
        operationalUntil: null
      },
      {
        icaoCode: 'CYVR',
        iataCode: 'YVR',
        name: 'Vancouver International Airport',
        city: 'Vancouver',
        country: 'Canada',
        latitude: 49.1947,
        longitude: -123.1839,
        elevation: 14,
        type: 'Major',
        timezone: 'America/Vancouver',
        operationalFrom: 1931,
        operationalUntil: null
      },
      {
        icaoCode: 'CYUL',
        iataCode: 'YUL',
        name: 'Montréal-Pierre Elliott Trudeau International Airport',
        city: 'Montreal',
        country: 'Canada',
        latitude: 45.4657,
        longitude: -73.7455,
        elevation: 118,
        type: 'Major',
        timezone: 'America/Toronto',
        operationalFrom: 1941,
        operationalUntil: null
      },
      {
        icaoCode: 'CYYC',
        iataCode: 'YYC',
        name: 'Calgary International Airport',
        city: 'Calgary',
        country: 'Canada',
        latitude: 51.1225,
        longitude: -114.0132,
        elevation: 3557,
        type: 'Major',
        timezone: 'America/Edmonton',
        operationalFrom: 1938,
        operationalUntil: null
      },

      // Mexico & Central America
      {
        icaoCode: 'MMMX',
        iataCode: 'MEX',
        name: 'Mexico City International Airport',
        city: 'Mexico City',
        country: 'Mexico',
        latitude: 19.4363,
        longitude: -99.0721,
        elevation: 7316,
        type: 'International Hub',
        timezone: 'America/Mexico_City',
        operationalFrom: 1931,
        operationalUntil: null
      },
      {
        icaoCode: 'MMUN',
        iataCode: 'CUN',
        name: 'Cancún International Airport',
        city: 'Cancún',
        country: 'Mexico',
        latitude: 21.0365,
        longitude: -86.8771,
        elevation: 22,
        type: 'Major',
        timezone: 'America/Cancun',
        operationalFrom: 1974,
        operationalUntil: null
      },
      {
        icaoCode: 'MGGT',
        iataCode: 'GUA',
        name: 'La Aurora International Airport',
        city: 'Guatemala City',
        country: 'Guatemala',
        latitude: 14.5833,
        longitude: -90.5275,
        elevation: 4952,
        type: 'Regional',
        timezone: 'America/Guatemala',
        operationalFrom: 1934,
        operationalUntil: null
      },
      {
        icaoCode: 'MROC',
        iataCode: 'SJO',
        name: 'Juan Santamaría International Airport',
        city: 'San José',
        country: 'Costa Rica',
        latitude: 9.9939,
        longitude: -84.2088,
        elevation: 3021,
        type: 'Regional',
        timezone: 'America/Costa_Rica',
        operationalFrom: 1958,
        operationalUntil: null
      },
      {
        icaoCode: 'MPTO',
        iataCode: 'PTY',
        name: 'Tocumen International Airport',
        city: 'Panama City',
        country: 'Panama',
        latitude: 9.0714,
        longitude: -79.3835,
        elevation: 135,
        type: 'Major',
        timezone: 'America/Panama',
        operationalFrom: 1947,
        operationalUntil: null
      },

      // ==================== EUROPE ====================

      // United Kingdom
      {
        icaoCode: 'EGLL',
        iataCode: 'LHR',
        name: 'London Heathrow Airport',
        city: 'London',
        country: 'United Kingdom',
        latitude: 51.4700,
        longitude: -0.4543,
        elevation: 83,
        type: 'International Hub',
        timezone: 'Europe/London',
        operationalFrom: 1946,
        operationalUntil: null
      },
      {
        icaoCode: 'EGKK',
        iataCode: 'LGW',
        name: 'London Gatwick Airport',
        city: 'London',
        country: 'United Kingdom',
        latitude: 51.1537,
        longitude: -0.1821,
        elevation: 202,
        type: 'Major',
        timezone: 'Europe/London',
        operationalFrom: 1930,
        operationalUntil: null
      },
      {
        icaoCode: 'EGSS',
        iataCode: 'STN',
        name: 'London Stansted Airport',
        city: 'London',
        country: 'United Kingdom',
        latitude: 51.8860,
        longitude: 0.2389,
        elevation: 348,
        type: 'Major',
        timezone: 'Europe/London',
        operationalFrom: 1942,
        operationalUntil: null
      },
      {
        icaoCode: 'EGCC',
        iataCode: 'MAN',
        name: 'Manchester Airport',
        city: 'Manchester',
        country: 'United Kingdom',
        latitude: 53.3615,
        longitude: -2.2750,
        elevation: 257,
        type: 'Major',
        timezone: 'Europe/London',
        operationalFrom: 1938,
        operationalUntil: null
      },
      {
        icaoCode: 'EGPH',
        iataCode: 'EDI',
        name: 'Edinburgh Airport',
        city: 'Edinburgh',
        country: 'United Kingdom',
        latitude: 55.9500,
        longitude: -3.3725,
        elevation: 135,
        type: 'Regional',
        timezone: 'Europe/London',
        operationalFrom: 1916,
        operationalUntil: null
      },

      // France
      {
        icaoCode: 'LFPG',
        iataCode: 'CDG',
        name: 'Charles de Gaulle Airport',
        city: 'Paris',
        country: 'France',
        latitude: 49.0097,
        longitude: 2.5479,
        elevation: 392,
        type: 'International Hub',
        timezone: 'Europe/Paris',
        operationalFrom: 1974,
        operationalUntil: null
      },
      {
        icaoCode: 'LFPO',
        iataCode: 'ORY',
        name: 'Paris Orly Airport',
        city: 'Paris',
        country: 'France',
        latitude: 48.7233,
        longitude: 2.3794,
        elevation: 291,
        type: 'Major',
        timezone: 'Europe/Paris',
        operationalFrom: 1932,
        operationalUntil: null
      },
      {
        icaoCode: 'LFML',
        iataCode: 'MRS',
        name: 'Marseille Provence Airport',
        city: 'Marseille',
        country: 'France',
        latitude: 43.4393,
        longitude: 5.2214,
        elevation: 74,
        type: 'Regional',
        timezone: 'Europe/Paris',
        operationalFrom: 1922,
        operationalUntil: null
      },
      {
        icaoCode: 'LFLL',
        iataCode: 'LYS',
        name: 'Lyon-Saint Exupéry Airport',
        city: 'Lyon',
        country: 'France',
        latitude: 45.7256,
        longitude: 5.0811,
        elevation: 821,
        type: 'Regional',
        timezone: 'Europe/Paris',
        operationalFrom: 1975,
        operationalUntil: null
      },

      // Germany
      {
        icaoCode: 'EDDF',
        iataCode: 'FRA',
        name: 'Frankfurt Airport',
        city: 'Frankfurt',
        country: 'Germany',
        latitude: 50.0379,
        longitude: 8.5622,
        elevation: 364,
        type: 'International Hub',
        timezone: 'Europe/Berlin',
        operationalFrom: 1936,
        operationalUntil: null
      },
      {
        icaoCode: 'EDDM',
        iataCode: 'MUC',
        name: 'Munich Airport',
        city: 'Munich',
        country: 'Germany',
        latitude: 48.3538,
        longitude: 11.7861,
        elevation: 1487,
        type: 'Major',
        timezone: 'Europe/Berlin',
        operationalFrom: 1992,
        operationalUntil: null
      },
      {
        icaoCode: 'EDDB',
        iataCode: 'BER',
        name: 'Berlin Brandenburg Airport',
        city: 'Berlin',
        country: 'Germany',
        latitude: 52.3667,
        longitude: 13.5033,
        elevation: 157,
        type: 'Major',
        timezone: 'Europe/Berlin',
        operationalFrom: 2020,
        operationalUntil: null
      },
      {
        icaoCode: 'EDDH',
        iataCode: 'HAM',
        name: 'Hamburg Airport',
        city: 'Hamburg',
        country: 'Germany',
        latitude: 53.6304,
        longitude: 9.9882,
        elevation: 53,
        type: 'Regional',
        timezone: 'Europe/Berlin',
        operationalFrom: 1911,
        operationalUntil: null
      },
      {
        icaoCode: 'EDDT',
        iataCode: 'TXL',
        name: 'Berlin Tegel Airport',
        city: 'Berlin',
        country: 'Germany',
        latitude: 52.5597,
        longitude: 13.2877,
        elevation: 122,
        type: 'Major',
        timezone: 'Europe/Berlin',
        operationalFrom: 1948,
        operationalUntil: 2020
      },
      {
        icaoCode: 'EDDI',
        iataCode: 'THF',
        name: 'Berlin Tempelhof Airport',
        city: 'Berlin',
        country: 'Germany',
        latitude: 52.4728,
        longitude: 13.4039,
        elevation: 167,
        type: 'Regional',
        timezone: 'Europe/Berlin',
        operationalFrom: 1923,
        operationalUntil: 2008
      },

      // Netherlands
      {
        icaoCode: 'EHAM',
        iataCode: 'AMS',
        name: 'Amsterdam Airport Schiphol',
        city: 'Amsterdam',
        country: 'Netherlands',
        latitude: 52.3105,
        longitude: 4.7683,
        elevation: -11,
        type: 'International Hub',
        timezone: 'Europe/Amsterdam',
        operationalFrom: 1916,
        operationalUntil: null
      },

      // Spain
      {
        icaoCode: 'LEMD',
        iataCode: 'MAD',
        name: 'Adolfo Suárez Madrid-Barajas Airport',
        city: 'Madrid',
        country: 'Spain',
        latitude: 40.4983,
        longitude: -3.5676,
        elevation: 1998,
        type: 'International Hub',
        timezone: 'Europe/Madrid',
        operationalFrom: 1928,
        operationalUntil: null
      },
      {
        icaoCode: 'LEBL',
        iataCode: 'BCN',
        name: 'Barcelona-El Prat Airport',
        city: 'Barcelona',
        country: 'Spain',
        latitude: 41.2974,
        longitude: 2.0833,
        elevation: 12,
        type: 'Major',
        timezone: 'Europe/Madrid',
        operationalFrom: 1916,
        operationalUntil: null
      },
      {
        icaoCode: 'LEPA',
        iataCode: 'PMI',
        name: 'Palma de Mallorca Airport',
        city: 'Palma',
        country: 'Spain',
        latitude: 39.5517,
        longitude: 2.7388,
        elevation: 27,
        type: 'Regional',
        timezone: 'Europe/Madrid',
        operationalFrom: 1960,
        operationalUntil: null
      },

      // Italy
      {
        icaoCode: 'LIRF',
        iataCode: 'FCO',
        name: 'Leonardo da Vinci-Fiumicino Airport',
        city: 'Rome',
        country: 'Italy',
        latitude: 41.8003,
        longitude: 12.2389,
        elevation: 13,
        type: 'Major',
        timezone: 'Europe/Rome',
        operationalFrom: 1961,
        operationalUntil: null
      },
      {
        icaoCode: 'LIMC',
        iataCode: 'MXP',
        name: 'Milan Malpensa Airport',
        city: 'Milan',
        country: 'Italy',
        latitude: 45.6306,
        longitude: 8.7281,
        elevation: 768,
        type: 'Major',
        timezone: 'Europe/Rome',
        operationalFrom: 1948,
        operationalUntil: null
      },
      {
        icaoCode: 'LIPZ',
        iataCode: 'VCE',
        name: 'Venice Marco Polo Airport',
        city: 'Venice',
        country: 'Italy',
        latitude: 45.5053,
        longitude: 12.3519,
        elevation: 7,
        type: 'Regional',
        timezone: 'Europe/Rome',
        operationalFrom: 1960,
        operationalUntil: null
      },

      // Switzerland
      {
        icaoCode: 'LSZH',
        iataCode: 'ZRH',
        name: 'Zurich Airport',
        city: 'Zurich',
        country: 'Switzerland',
        latitude: 47.4647,
        longitude: 8.5492,
        elevation: 1416,
        type: 'Major',
        timezone: 'Europe/Zurich',
        operationalFrom: 1948,
        operationalUntil: null
      },
      {
        icaoCode: 'LSGG',
        iataCode: 'GVA',
        name: 'Geneva Airport',
        city: 'Geneva',
        country: 'Switzerland',
        latitude: 46.2381,
        longitude: 6.1089,
        elevation: 1411,
        type: 'Regional',
        timezone: 'Europe/Zurich',
        operationalFrom: 1920,
        operationalUntil: null
      },

      // Austria
      {
        icaoCode: 'LOWW',
        iataCode: 'VIE',
        name: 'Vienna International Airport',
        city: 'Vienna',
        country: 'Austria',
        latitude: 48.1103,
        longitude: 16.5697,
        elevation: 600,
        type: 'Major',
        timezone: 'Europe/Vienna',
        operationalFrom: 1954,
        operationalUntil: null
      },

      // Belgium
      {
        icaoCode: 'EBBR',
        iataCode: 'BRU',
        name: 'Brussels Airport',
        city: 'Brussels',
        country: 'Belgium',
        latitude: 50.9014,
        longitude: 4.4844,
        elevation: 184,
        type: 'Major',
        timezone: 'Europe/Brussels',
        operationalFrom: 1940,
        operationalUntil: null
      },

      // Portugal
      {
        icaoCode: 'LPPT',
        iataCode: 'LIS',
        name: 'Lisbon Portela Airport',
        city: 'Lisbon',
        country: 'Portugal',
        latitude: 38.7742,
        longitude: -9.1342,
        elevation: 374,
        type: 'Major',
        timezone: 'Europe/Lisbon',
        operationalFrom: 1942,
        operationalUntil: null
      },

      // Ireland
      {
        icaoCode: 'EIDW',
        iataCode: 'DUB',
        name: 'Dublin Airport',
        city: 'Dublin',
        country: 'Ireland',
        latitude: 53.4213,
        longitude: -6.2701,
        elevation: 242,
        type: 'Major',
        timezone: 'Europe/Dublin',
        operationalFrom: 1940,
        operationalUntil: null
      },

      // Scandinavia
      {
        icaoCode: 'EKCH',
        iataCode: 'CPH',
        name: 'Copenhagen Airport',
        city: 'Copenhagen',
        country: 'Denmark',
        latitude: 55.6180,
        longitude: 12.6560,
        elevation: 17,
        type: 'Major',
        timezone: 'Europe/Copenhagen',
        operationalFrom: 1925,
        operationalUntil: null
      },
      {
        icaoCode: 'ESSA',
        iataCode: 'ARN',
        name: 'Stockholm Arlanda Airport',
        city: 'Stockholm',
        country: 'Sweden',
        latitude: 59.6519,
        longitude: 17.9186,
        elevation: 137,
        type: 'Major',
        timezone: 'Europe/Stockholm',
        operationalFrom: 1959,
        operationalUntil: null
      },
      {
        icaoCode: 'ENGM',
        iataCode: 'OSL',
        name: 'Oslo Airport',
        city: 'Oslo',
        country: 'Norway',
        latitude: 60.1939,
        longitude: 11.1004,
        elevation: 681,
        type: 'Major',
        timezone: 'Europe/Oslo',
        operationalFrom: 1998,
        operationalUntil: null
      },
      {
        icaoCode: 'EFHK',
        iataCode: 'HEL',
        name: 'Helsinki-Vantaa Airport',
        city: 'Helsinki',
        country: 'Finland',
        latitude: 60.3172,
        longitude: 24.9633,
        elevation: 179,
        type: 'Major',
        timezone: 'Europe/Helsinki',
        operationalFrom: 1952,
        operationalUntil: null
      },

      // Eastern Europe
      {
        icaoCode: 'LHBP',
        iataCode: 'BUD',
        name: 'Budapest Ferenc Liszt International Airport',
        city: 'Budapest',
        country: 'Hungary',
        latitude: 47.4398,
        longitude: 19.2618,
        elevation: 495,
        type: 'Regional',
        timezone: 'Europe/Budapest',
        operationalFrom: 1950,
        operationalUntil: null
      },
      {
        icaoCode: 'LKPR',
        iataCode: 'PRG',
        name: 'Václav Havel Airport Prague',
        city: 'Prague',
        country: 'Czech Republic',
        latitude: 50.1008,
        longitude: 14.2600,
        elevation: 1247,
        type: 'Regional',
        timezone: 'Europe/Prague',
        operationalFrom: 1937,
        operationalUntil: null
      },
      {
        icaoCode: 'EPWA',
        iataCode: 'WAW',
        name: 'Warsaw Chopin Airport',
        city: 'Warsaw',
        country: 'Poland',
        latitude: 52.1657,
        longitude: 20.9671,
        elevation: 362,
        type: 'Major',
        timezone: 'Europe/Warsaw',
        operationalFrom: 1934,
        operationalUntil: null
      },

      // Russia & Turkey
      {
        icaoCode: 'UUEE',
        iataCode: 'SVO',
        name: 'Sheremetyevo International Airport',
        city: 'Moscow',
        country: 'Russia',
        latitude: 55.9726,
        longitude: 37.4146,
        elevation: 622,
        type: 'International Hub',
        timezone: 'Europe/Moscow',
        operationalFrom: 1959,
        operationalUntil: null
      },
      {
        icaoCode: 'UUDD',
        iataCode: 'DME',
        name: 'Domodedovo International Airport',
        city: 'Moscow',
        country: 'Russia',
        latitude: 55.4088,
        longitude: 37.9063,
        elevation: 588,
        type: 'Major',
        timezone: 'Europe/Moscow',
        operationalFrom: 1962,
        operationalUntil: null
      },
      {
        icaoCode: 'LTFM',
        iataCode: 'IST',
        name: 'Istanbul Airport',
        city: 'Istanbul',
        country: 'Turkey',
        latitude: 41.2753,
        longitude: 28.7519,
        elevation: 325,
        type: 'International Hub',
        timezone: 'Europe/Istanbul',
        operationalFrom: 2018,
        operationalUntil: null
      },
      {
        icaoCode: 'LTBA',
        iataCode: 'IST',
        name: 'Istanbul Atatürk Airport',
        city: 'Istanbul',
        country: 'Turkey',
        latitude: 40.9769,
        longitude: 28.8146,
        elevation: 163,
        type: 'International Hub',
        timezone: 'Europe/Istanbul',
        operationalFrom: 1953,
        operationalUntil: 2019
      },

      // ==================== ASIA ====================

      // Japan
      {
        icaoCode: 'RJTT',
        iataCode: 'HND',
        name: 'Tokyo Haneda Airport',
        city: 'Tokyo',
        country: 'Japan',
        latitude: 35.5494,
        longitude: 139.7798,
        elevation: 35,
        type: 'International Hub',
        timezone: 'Asia/Tokyo',
        operationalFrom: 1931,
        operationalUntil: null
      },
      {
        icaoCode: 'RJAA',
        iataCode: 'NRT',
        name: 'Narita International Airport',
        city: 'Tokyo',
        country: 'Japan',
        latitude: 35.7647,
        longitude: 140.3864,
        elevation: 141,
        type: 'International Hub',
        timezone: 'Asia/Tokyo',
        operationalFrom: 1978,
        operationalUntil: null
      },
      {
        icaoCode: 'RJBB',
        iataCode: 'KIX',
        name: 'Kansai International Airport',
        city: 'Osaka',
        country: 'Japan',
        latitude: 34.4273,
        longitude: 135.2444,
        elevation: 26,
        type: 'Major',
        timezone: 'Asia/Tokyo',
        operationalFrom: 1994,
        operationalUntil: null
      },
      {
        icaoCode: 'RJGG',
        iataCode: 'NGO',
        name: 'Chubu Centrair International Airport',
        city: 'Nagoya',
        country: 'Japan',
        latitude: 34.8584,
        longitude: 136.8054,
        elevation: 15,
        type: 'Regional',
        timezone: 'Asia/Tokyo',
        operationalFrom: 2005,
        operationalUntil: null
      },

      // Hong Kong
      {
        icaoCode: 'VHHH',
        iataCode: 'HKG',
        name: 'Hong Kong International Airport',
        city: 'Hong Kong',
        country: 'Hong Kong',
        latitude: 22.3080,
        longitude: 113.9185,
        elevation: 28,
        type: 'International Hub',
        timezone: 'Asia/Hong_Kong',
        operationalFrom: 1998,
        operationalUntil: null
      },
      {
        icaoCode: 'VHHX',
        iataCode: 'HKG',
        name: 'Kai Tak Airport',
        city: 'Kowloon',
        country: 'Hong Kong',
        latitude: 22.3364,
        longitude: 114.1914,
        elevation: 28,
        type: 'International Hub',
        timezone: 'Asia/Hong_Kong',
        operationalFrom: 1925,
        operationalUntil: 1998
      },

      // Singapore
      {
        icaoCode: 'WSSS',
        iataCode: 'SIN',
        name: 'Singapore Changi Airport',
        city: 'Singapore',
        country: 'Singapore',
        latitude: 1.3644,
        longitude: 103.9915,
        elevation: 22,
        type: 'International Hub',
        timezone: 'Asia/Singapore',
        operationalFrom: 1981,
        operationalUntil: null
      },

      // China
      {
        icaoCode: 'ZSPD',
        iataCode: 'PVG',
        name: 'Shanghai Pudong International Airport',
        city: 'Shanghai',
        country: 'China',
        latitude: 31.1443,
        longitude: 121.8083,
        elevation: 13,
        type: 'International Hub',
        timezone: 'Asia/Shanghai',
        operationalFrom: 1999,
        operationalUntil: null
      },
      {
        icaoCode: 'ZBAA',
        iataCode: 'PEK',
        name: 'Beijing Capital International Airport',
        city: 'Beijing',
        country: 'China',
        latitude: 40.0801,
        longitude: 116.5846,
        elevation: 116,
        type: 'International Hub',
        timezone: 'Asia/Shanghai',
        operationalFrom: 1958,
        operationalUntil: null
      },
      {
        icaoCode: 'ZGGG',
        iataCode: 'CAN',
        name: 'Guangzhou Baiyun International Airport',
        city: 'Guangzhou',
        country: 'China',
        latitude: 23.3924,
        longitude: 113.2988,
        elevation: 50,
        type: 'Major',
        timezone: 'Asia/Shanghai',
        operationalFrom: 2004,
        operationalUntil: null
      },
      {
        icaoCode: 'ZGSZ',
        iataCode: 'SZX',
        name: 'Shenzhen Bao\'an International Airport',
        city: 'Shenzhen',
        country: 'China',
        latitude: 22.6393,
        longitude: 113.8107,
        elevation: 13,
        type: 'Major',
        timezone: 'Asia/Shanghai',
        operationalFrom: 1991,
        operationalUntil: null
      },

      // South Korea
      {
        icaoCode: 'RKSI',
        iataCode: 'ICN',
        name: 'Incheon International Airport',
        city: 'Seoul',
        country: 'South Korea',
        latitude: 37.4602,
        longitude: 126.4407,
        elevation: 23,
        type: 'International Hub',
        timezone: 'Asia/Seoul',
        operationalFrom: 2001,
        operationalUntil: null
      },
      {
        icaoCode: 'RKSS',
        iataCode: 'GMP',
        name: 'Gimpo International Airport',
        city: 'Seoul',
        country: 'South Korea',
        latitude: 37.5583,
        longitude: 126.7906,
        elevation: 59,
        type: 'Regional',
        timezone: 'Asia/Seoul',
        operationalFrom: 1939,
        operationalUntil: null
      },

      // Southeast Asia
      {
        icaoCode: 'VTBS',
        iataCode: 'BKK',
        name: 'Suvarnabhumi Airport',
        city: 'Bangkok',
        country: 'Thailand',
        latitude: 13.6900,
        longitude: 100.7501,
        elevation: 5,
        type: 'International Hub',
        timezone: 'Asia/Bangkok',
        operationalFrom: 2006,
        operationalUntil: null
      },
      {
        icaoCode: 'VTBD',
        iataCode: 'DMK',
        name: 'Don Mueang International Airport',
        city: 'Bangkok',
        country: 'Thailand',
        latitude: 13.9126,
        longitude: 100.6070,
        elevation: 9,
        type: 'Regional',
        timezone: 'Asia/Bangkok',
        operationalFrom: 1914,
        operationalUntil: null
      },
      {
        icaoCode: 'WMKK',
        iataCode: 'KUL',
        name: 'Kuala Lumpur International Airport',
        city: 'Kuala Lumpur',
        country: 'Malaysia',
        latitude: 2.7456,
        longitude: 101.7099,
        elevation: 69,
        type: 'Major',
        timezone: 'Asia/Kuala_Lumpur',
        operationalFrom: 1998,
        operationalUntil: null
      },
      {
        icaoCode: 'WIII',
        iataCode: 'CGK',
        name: 'Soekarno-Hatta International Airport',
        city: 'Jakarta',
        country: 'Indonesia',
        latitude: -6.1256,
        longitude: 106.6559,
        elevation: 34,
        type: 'Major',
        timezone: 'Asia/Jakarta',
        operationalFrom: 1985,
        operationalUntil: null
      },
      {
        icaoCode: 'RPLL',
        iataCode: 'MNL',
        name: 'Ninoy Aquino International Airport',
        city: 'Manila',
        country: 'Philippines',
        latitude: 14.5086,
        longitude: 121.0194,
        elevation: 75,
        type: 'Major',
        timezone: 'Asia/Manila',
        operationalFrom: 1948,
        operationalUntil: null
      },
      {
        icaoCode: 'VDPP',
        iataCode: 'PNH',
        name: 'Phnom Penh International Airport',
        city: 'Phnom Penh',
        country: 'Cambodia',
        latitude: 11.5466,
        longitude: 104.8441,
        elevation: 40,
        type: 'Regional',
        timezone: 'Asia/Phnom_Penh',
        operationalFrom: 1995,
        operationalUntil: null
      },
      {
        icaoCode: 'VVNB',
        iataCode: 'HAN',
        name: 'Noi Bai International Airport',
        city: 'Hanoi',
        country: 'Vietnam',
        latitude: 21.2212,
        longitude: 105.8072,
        elevation: 39,
        type: 'Regional',
        timezone: 'Asia/Ho_Chi_Minh',
        operationalFrom: 1978,
        operationalUntil: null
      },
      {
        icaoCode: 'VVTS',
        iataCode: 'SGN',
        name: 'Tan Son Nhat International Airport',
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        latitude: 10.8188,
        longitude: 106.6519,
        elevation: 33,
        type: 'Major',
        timezone: 'Asia/Ho_Chi_Minh',
        operationalFrom: 1930,
        operationalUntil: null
      },

      // India
      {
        icaoCode: 'VIDP',
        iataCode: 'DEL',
        name: 'Indira Gandhi International Airport',
        city: 'New Delhi',
        country: 'India',
        latitude: 28.5562,
        longitude: 77.1000,
        elevation: 777,
        type: 'International Hub',
        timezone: 'Asia/Kolkata',
        operationalFrom: 1962,
        operationalUntil: null
      },
      {
        icaoCode: 'VABB',
        iataCode: 'BOM',
        name: 'Chhatrapati Shivaji Maharaj International Airport',
        city: 'Mumbai',
        country: 'India',
        latitude: 19.0896,
        longitude: 72.8656,
        elevation: 39,
        type: 'Major',
        timezone: 'Asia/Kolkata',
        operationalFrom: 1942,
        operationalUntil: null
      },
      {
        icaoCode: 'VOBL',
        iataCode: 'BLR',
        name: 'Kempegowda International Airport',
        city: 'Bangalore',
        country: 'India',
        latitude: 13.1979,
        longitude: 77.7063,
        elevation: 3000,
        type: 'Major',
        timezone: 'Asia/Kolkata',
        operationalFrom: 2008,
        operationalUntil: null
      },

      // Middle East
      {
        icaoCode: 'OMDB',
        iataCode: 'DXB',
        name: 'Dubai International Airport',
        city: 'Dubai',
        country: 'United Arab Emirates',
        latitude: 25.2532,
        longitude: 55.3657,
        elevation: 62,
        type: 'International Hub',
        timezone: 'Asia/Dubai',
        operationalFrom: 1960,
        operationalUntil: null
      },
      {
        icaoCode: 'OTHH',
        iataCode: 'DOH',
        name: 'Hamad International Airport',
        city: 'Doha',
        country: 'Qatar',
        latitude: 25.2731,
        longitude: 51.6080,
        elevation: 13,
        type: 'International Hub',
        timezone: 'Asia/Qatar',
        operationalFrom: 2014,
        operationalUntil: null
      },
      {
        icaoCode: 'OERK',
        iataCode: 'RUH',
        name: 'King Khalid International Airport',
        city: 'Riyadh',
        country: 'Saudi Arabia',
        latitude: 24.9576,
        longitude: 46.6988,
        elevation: 2049,
        type: 'Major',
        timezone: 'Asia/Riyadh',
        operationalFrom: 1983,
        operationalUntil: null
      },
      {
        icaoCode: 'OEJN',
        iataCode: 'JED',
        name: 'King Abdulaziz International Airport',
        city: 'Jeddah',
        country: 'Saudi Arabia',
        latitude: 21.6796,
        longitude: 39.1565,
        elevation: 48,
        type: 'Major',
        timezone: 'Asia/Riyadh',
        operationalFrom: 1981,
        operationalUntil: null
      },

      // ==================== OCEANIA ====================

      {
        icaoCode: 'YSSY',
        iataCode: 'SYD',
        name: 'Sydney Kingsford Smith Airport',
        city: 'Sydney',
        country: 'Australia',
        latitude: -33.9399,
        longitude: 151.1753,
        elevation: 21,
        type: 'International Hub',
        timezone: 'Australia/Sydney',
        operationalFrom: 1920,
        operationalUntil: null
      },
      {
        icaoCode: 'YMML',
        iataCode: 'MEL',
        name: 'Melbourne Airport',
        city: 'Melbourne',
        country: 'Australia',
        latitude: -37.6690,
        longitude: 144.8410,
        elevation: 434,
        type: 'Major',
        timezone: 'Australia/Melbourne',
        operationalFrom: 1970,
        operationalUntil: null
      },
      {
        icaoCode: 'YBBN',
        iataCode: 'BNE',
        name: 'Brisbane Airport',
        city: 'Brisbane',
        country: 'Australia',
        latitude: -27.3942,
        longitude: 153.1218,
        elevation: 13,
        type: 'Major',
        timezone: 'Australia/Brisbane',
        operationalFrom: 1988,
        operationalUntil: null
      },
      {
        icaoCode: 'YPPH',
        iataCode: 'PER',
        name: 'Perth Airport',
        city: 'Perth',
        country: 'Australia',
        latitude: -31.9403,
        longitude: 115.9672,
        elevation: 67,
        type: 'Major',
        timezone: 'Australia/Perth',
        operationalFrom: 1944,
        operationalUntil: null
      },
      {
        icaoCode: 'NZAA',
        iataCode: 'AKL',
        name: 'Auckland Airport',
        city: 'Auckland',
        country: 'New Zealand',
        latitude: -37.0082,
        longitude: 174.7850,
        elevation: 23,
        type: 'Major',
        timezone: 'Pacific/Auckland',
        operationalFrom: 1966,
        operationalUntil: null
      },
      {
        icaoCode: 'NZCH',
        iataCode: 'CHC',
        name: 'Christchurch International Airport',
        city: 'Christchurch',
        country: 'New Zealand',
        latitude: -43.4894,
        longitude: 172.5320,
        elevation: 123,
        type: 'Regional',
        timezone: 'Pacific/Auckland',
        operationalFrom: 1940,
        operationalUntil: null
      },

      // ==================== SOUTH AMERICA ====================

      {
        icaoCode: 'SBGR',
        iataCode: 'GRU',
        name: 'São Paulo/Guarulhos International Airport',
        city: 'São Paulo',
        country: 'Brazil',
        latitude: -23.4356,
        longitude: -46.4731,
        elevation: 2459,
        type: 'International Hub',
        timezone: 'America/Sao_Paulo',
        operationalFrom: 1985,
        operationalUntil: null
      },
      {
        icaoCode: 'SBGL',
        iataCode: 'GIG',
        name: 'Rio de Janeiro-Galeão International Airport',
        city: 'Rio de Janeiro',
        country: 'Brazil',
        latitude: -22.8099,
        longitude: -43.2506,
        elevation: 28,
        type: 'Major',
        timezone: 'America/Sao_Paulo',
        operationalFrom: 1952,
        operationalUntil: null
      },
      {
        icaoCode: 'SBBR',
        iataCode: 'BSB',
        name: 'Brasília International Airport',
        city: 'Brasília',
        country: 'Brazil',
        latitude: -15.8697,
        longitude: -47.9208,
        elevation: 3497,
        type: 'Major',
        timezone: 'America/Sao_Paulo',
        operationalFrom: 1957,
        operationalUntil: null
      },
      {
        icaoCode: 'SAEZ',
        iataCode: 'EZE',
        name: 'Ministro Pistarini International Airport',
        city: 'Buenos Aires',
        country: 'Argentina',
        latitude: -34.8222,
        longitude: -58.5358,
        elevation: 67,
        type: 'Major',
        timezone: 'America/Argentina/Buenos_Aires',
        operationalFrom: 1949,
        operationalUntil: null
      },
      {
        icaoCode: 'SCEL',
        iataCode: 'SCL',
        name: 'Arturo Merino Benítez International Airport',
        city: 'Santiago',
        country: 'Chile',
        latitude: -33.3930,
        longitude: -70.7858,
        elevation: 1555,
        type: 'Major',
        timezone: 'America/Santiago',
        operationalFrom: 1967,
        operationalUntil: null
      },
      {
        icaoCode: 'SKBO',
        iataCode: 'BOG',
        name: 'El Dorado International Airport',
        city: 'Bogotá',
        country: 'Colombia',
        latitude: 4.7016,
        longitude: -74.1469,
        elevation: 8361,
        type: 'Major',
        timezone: 'America/Bogota',
        operationalFrom: 1959,
        operationalUntil: null
      },
      {
        icaoCode: 'SPJC',
        iataCode: 'LIM',
        name: 'Jorge Chávez International Airport',
        city: 'Lima',
        country: 'Peru',
        latitude: -12.0219,
        longitude: -77.1143,
        elevation: 113,
        type: 'Major',
        timezone: 'America/Lima',
        operationalFrom: 1960,
        operationalUntil: null
      },

      // ==================== AFRICA ====================

      {
        icaoCode: 'FACT',
        iataCode: 'CPT',
        name: 'Cape Town International Airport',
        city: 'Cape Town',
        country: 'South Africa',
        latitude: -33.9715,
        longitude: 18.6021,
        elevation: 151,
        type: 'Major',
        timezone: 'Africa/Johannesburg',
        operationalFrom: 1954,
        operationalUntil: null
      },
      {
        icaoCode: 'FAOR',
        iataCode: 'JNB',
        name: 'O.R. Tambo International Airport',
        city: 'Johannesburg',
        country: 'South Africa',
        latitude: -26.1392,
        longitude: 28.2460,
        elevation: 5558,
        type: 'International Hub',
        timezone: 'Africa/Johannesburg',
        operationalFrom: 1952,
        operationalUntil: null
      },
      {
        icaoCode: 'HECA',
        iataCode: 'CAI',
        name: 'Cairo International Airport',
        city: 'Cairo',
        country: 'Egypt',
        latitude: 30.1219,
        longitude: 31.4056,
        elevation: 382,
        type: 'Major',
        timezone: 'Africa/Cairo',
        operationalFrom: 1963,
        operationalUntil: null
      },
      {
        icaoCode: 'GMMN',
        iataCode: 'CMN',
        name: 'Mohammed V International Airport',
        city: 'Casablanca',
        country: 'Morocco',
        latitude: 33.3675,
        longitude: -7.5898,
        elevation: 656,
        type: 'Major',
        timezone: 'Africa/Casablanca',
        operationalFrom: 1953,
        operationalUntil: null
      },
      {
        icaoCode: 'DNMM',
        iataCode: 'LOS',
        name: 'Murtala Muhammed International Airport',
        city: 'Lagos',
        country: 'Nigeria',
        latitude: 6.5774,
        longitude: 3.3212,
        elevation: 135,
        type: 'Major',
        timezone: 'Africa/Lagos',
        operationalFrom: 1979,
        operationalUntil: null
      },
      {
        icaoCode: 'HKJK',
        iataCode: 'NBO',
        name: 'Jomo Kenyatta International Airport',
        city: 'Nairobi',
        country: 'Kenya',
        latitude: -1.3192,
        longitude: 36.9278,
        elevation: 5327,
        type: 'Major',
        timezone: 'Africa/Nairobi',
        operationalFrom: 1978,
        operationalUntil: null
      },
      {
        icaoCode: 'HAAB',
        iataCode: 'ADD',
        name: 'Addis Ababa Bole International Airport',
        city: 'Addis Ababa',
        country: 'Ethiopia',
        latitude: 8.9779,
        longitude: 38.7993,
        elevation: 7625,
        type: 'Major',
        timezone: 'Africa/Addis_Ababa',
        operationalFrom: 1961,
        operationalUntil: null
      },

      // ==================== CARIBBEAN ====================

      {
        icaoCode: 'TJSJ',
        iataCode: 'SJU',
        name: 'Luis Muñoz Marín International Airport',
        city: 'San Juan',
        country: 'Puerto Rico',
        latitude: 18.4394,
        longitude: -66.0018,
        elevation: 9,
        type: 'Regional',
        timezone: 'America/Puerto_Rico',
        operationalFrom: 1955,
        operationalUntil: null
      },
      {
        icaoCode: 'MKJP',
        iataCode: 'KIN',
        name: 'Norman Manley International Airport',
        city: 'Kingston',
        country: 'Jamaica',
        latitude: 17.9357,
        longitude: -76.7875,
        elevation: 10,
        type: 'Regional',
        timezone: 'America/Jamaica',
        operationalFrom: 1948,
        operationalUntil: null
      },
      {
        icaoCode: 'MDSD',
        iataCode: 'SDQ',
        name: 'Las Américas International Airport',
        city: 'Santo Domingo',
        country: 'Dominican Republic',
        latitude: 18.4297,
        longitude: -69.6689,
        elevation: 59,
        type: 'Regional',
        timezone: 'America/Santo_Domingo',
        operationalFrom: 1959,
        operationalUntil: null
      },
      {
        icaoCode: 'TNCM',
        iataCode: 'SXM',
        name: 'Princess Juliana International Airport',
        city: 'Philipsburg',
        country: 'Sint Maarten',
        latitude: 18.0410,
        longitude: -63.1089,
        elevation: 13,
        type: 'Small Regional',
        timezone: 'America/Lower_Princes',
        operationalFrom: 1943,
        operationalUntil: null
      }
    ];

    // Check if airports already exist
    const existingAirports = await Airport.count();

    if (existingAirports > 0) {
      console.log(`Found ${existingAirports} existing airports. Skipping seed.`);
      console.log('If you want to reseed, please truncate the airports table first.');
      process.exit(0);
    }

    // Create all airports
    await Airport.bulkCreate(airports);

    console.log(`✓ Successfully seeded ${airports.length} airports`);
    console.log('\nAirports by type:');
    console.log(`  - International Hubs: ${airports.filter(a => a.type === 'International Hub').length}`);
    console.log(`  - Major: ${airports.filter(a => a.type === 'Major').length}`);
    console.log(`  - Regional: ${airports.filter(a => a.type === 'Regional').length}`);
    console.log(`  - Small Regional: ${airports.filter(a => a.type === 'Small Regional').length}`);
    console.log('\nHistorical airports (closed):');
    const closedAirports = airports.filter(a => a.operationalUntil !== null);
    closedAirports.forEach(a => {
      console.log(`  - ${a.name} (${a.icaoCode}): ${a.operationalFrom} - ${a.operationalUntil}`);
    });

    process.exit(0);
  } catch (error) {
    console.error('✗ Airport seeding failed:', error);
    process.exit(1);
  }
}

seedAirports();
